#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace repaso
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PlanillaDePagoMensual")]
	public partial class DataClassesPlanillaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCargo(Cargo instance);
    partial void UpdateCargo(Cargo instance);
    partial void DeleteCargo(Cargo instance);
    partial void InsertEmpleado(Empleado instance);
    partial void UpdateEmpleado(Empleado instance);
    partial void DeleteEmpleado(Empleado instance);
    partial void InsertHoraExtra(HoraExtra instance);
    partial void UpdateHoraExtra(HoraExtra instance);
    partial void DeleteHoraExtra(HoraExtra instance);
    partial void InsertHoraFaltada(HoraFaltada instance);
    partial void UpdateHoraFaltada(HoraFaltada instance);
    partial void DeleteHoraFaltada(HoraFaltada instance);
    partial void InsertIHSS(IHSS instance);
    partial void UpdateIHSS(IHSS instance);
    partial void DeleteIHSS(IHSS instance);
    partial void InsertPlanillaFinal(PlanillaFinal instance);
    partial void UpdatePlanillaFinal(PlanillaFinal instance);
    partial void DeletePlanillaFinal(PlanillaFinal instance);
    partial void InsertPorcentajeHoraExtra(PorcentajeHoraExtra instance);
    partial void UpdatePorcentajeHoraExtra(PorcentajeHoraExtra instance);
    partial void DeletePorcentajeHoraExtra(PorcentajeHoraExtra instance);
    partial void InsertPrestacionLaboral(PrestacionLaboral instance);
    partial void UpdatePrestacionLaboral(PrestacionLaboral instance);
    partial void DeletePrestacionLaboral(PrestacionLaboral instance);
    partial void InsertPrestacionLaboralEmbarazo(PrestacionLaboralEmbarazo instance);
    partial void UpdatePrestacionLaboralEmbarazo(PrestacionLaboralEmbarazo instance);
    partial void DeletePrestacionLaboralEmbarazo(PrestacionLaboralEmbarazo instance);
    partial void InsertRAP(RAP instance);
    partial void UpdateRAP(RAP instance);
    partial void DeleteRAP(RAP instance);
    partial void InsertTelefonoEmpleado(TelefonoEmpleado instance);
    partial void UpdateTelefonoEmpleado(TelefonoEmpleado instance);
    partial void DeleteTelefonoEmpleado(TelefonoEmpleado instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    #endregion
		
		public DataClassesPlanillaDataContext() : 
				base(global::repaso.Properties.Settings.Default.PlanillaDePagoMensualConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesPlanillaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesPlanillaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesPlanillaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesPlanillaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cargo> Cargo
		{
			get
			{
				return this.GetTable<Cargo>();
			}
		}
		
		public System.Data.Linq.Table<Empleado> Empleado
		{
			get
			{
				return this.GetTable<Empleado>();
			}
		}
		
		public System.Data.Linq.Table<HoraExtra> HoraExtra
		{
			get
			{
				return this.GetTable<HoraExtra>();
			}
		}
		
		public System.Data.Linq.Table<HoraFaltada> HoraFaltada
		{
			get
			{
				return this.GetTable<HoraFaltada>();
			}
		}
		
		public System.Data.Linq.Table<IHSS> IHSS
		{
			get
			{
				return this.GetTable<IHSS>();
			}
		}
		
		public System.Data.Linq.Table<PlanillaFinal> PlanillaFinal
		{
			get
			{
				return this.GetTable<PlanillaFinal>();
			}
		}
		
		public System.Data.Linq.Table<PorcentajeHoraExtra> PorcentajeHoraExtra
		{
			get
			{
				return this.GetTable<PorcentajeHoraExtra>();
			}
		}
		
		public System.Data.Linq.Table<PrestacionLaboral> PrestacionLaboral
		{
			get
			{
				return this.GetTable<PrestacionLaboral>();
			}
		}
		
		public System.Data.Linq.Table<PrestacionLaboralEmbarazo> PrestacionLaboralEmbarazo
		{
			get
			{
				return this.GetTable<PrestacionLaboralEmbarazo>();
			}
		}
		
		public System.Data.Linq.Table<RAP> RAP
		{
			get
			{
				return this.GetTable<RAP>();
			}
		}
		
		public System.Data.Linq.Table<TelefonoEmpleado> TelefonoEmpleado
		{
			get
			{
				return this.GetTable<TelefonoEmpleado>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuario
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Planilla.Cargo")]
	public partial class Cargo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Codigo;
		
		private string _Nombre;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private EntitySet<Empleado> _Empleado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(string value);
    partial void OnCodigoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    #endregion
		
		public Cargo()
		{
			this._Empleado = new EntitySet<Empleado>(new Action<Empleado>(this.attach_Empleado), new Action<Empleado>(this.detach_Empleado));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cargo_Empleado", Storage="_Empleado", ThisKey="Codigo", OtherKey="CodigoCargo")]
		public EntitySet<Empleado> Empleado
		{
			get
			{
				return this._Empleado;
			}
			set
			{
				this._Empleado.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Empleado(Empleado entity)
		{
			this.SendPropertyChanging();
			entity.Cargo = this;
		}
		
		private void detach_Empleado(Empleado entity)
		{
			this.SendPropertyChanging();
			entity.Cargo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Planilla.Empleado")]
	public partial class Empleado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Identidad;
		
		private string _CodigoCargo;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private char _Genero;
		
		private decimal _SueldoOrdinario;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private string _NivelAcademico;
		
		private System.Nullable<bool> _Estado;
		
		private EntitySet<HoraExtra> _HoraExtra;
		
		private EntitySet<HoraFaltada> _HoraFaltada;
		
		private EntitySet<PlanillaFinal> _PlanillaFinal;
		
		private EntitySet<PrestacionLaboral> _PrestacionLaboral;
		
		private EntitySet<TelefonoEmpleado> _TelefonoEmpleado;
		
		private EntitySet<Usuario> _Usuario;
		
		private EntityRef<Cargo> _Cargo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdentidadChanging(string value);
    partial void OnIdentidadChanged();
    partial void OnCodigoCargoChanging(string value);
    partial void OnCodigoCargoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnGeneroChanging(char value);
    partial void OnGeneroChanged();
    partial void OnSueldoOrdinarioChanging(decimal value);
    partial void OnSueldoOrdinarioChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    partial void OnNivelAcademicoChanging(string value);
    partial void OnNivelAcademicoChanged();
    partial void OnEstadoChanging(System.Nullable<bool> value);
    partial void OnEstadoChanged();
    #endregion
		
		public Empleado()
		{
			this._HoraExtra = new EntitySet<HoraExtra>(new Action<HoraExtra>(this.attach_HoraExtra), new Action<HoraExtra>(this.detach_HoraExtra));
			this._HoraFaltada = new EntitySet<HoraFaltada>(new Action<HoraFaltada>(this.attach_HoraFaltada), new Action<HoraFaltada>(this.detach_HoraFaltada));
			this._PlanillaFinal = new EntitySet<PlanillaFinal>(new Action<PlanillaFinal>(this.attach_PlanillaFinal), new Action<PlanillaFinal>(this.detach_PlanillaFinal));
			this._PrestacionLaboral = new EntitySet<PrestacionLaboral>(new Action<PrestacionLaboral>(this.attach_PrestacionLaboral), new Action<PrestacionLaboral>(this.detach_PrestacionLaboral));
			this._TelefonoEmpleado = new EntitySet<TelefonoEmpleado>(new Action<TelefonoEmpleado>(this.attach_TelefonoEmpleado), new Action<TelefonoEmpleado>(this.detach_TelefonoEmpleado));
			this._Usuario = new EntitySet<Usuario>(new Action<Usuario>(this.attach_Usuario), new Action<Usuario>(this.detach_Usuario));
			this._Cargo = default(EntityRef<Cargo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identidad", DbType="Char(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Identidad
		{
			get
			{
				return this._Identidad;
			}
			set
			{
				if ((this._Identidad != value))
				{
					this.OnIdentidadChanging(value);
					this.SendPropertyChanging();
					this._Identidad = value;
					this.SendPropertyChanged("Identidad");
					this.OnIdentidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoCargo", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string CodigoCargo
		{
			get
			{
				return this._CodigoCargo;
			}
			set
			{
				if ((this._CodigoCargo != value))
				{
					if (this._Cargo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodigoCargoChanging(value);
					this.SendPropertyChanging();
					this._CodigoCargo = value;
					this.SendPropertyChanged("CodigoCargo");
					this.OnCodigoCargoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Genero", DbType="Char(1) NOT NULL")]
		public char Genero
		{
			get
			{
				return this._Genero;
			}
			set
			{
				if ((this._Genero != value))
				{
					this.OnGeneroChanging(value);
					this.SendPropertyChanging();
					this._Genero = value;
					this.SendPropertyChanged("Genero");
					this.OnGeneroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SueldoOrdinario", DbType="Decimal(10,2) NOT NULL")]
		public decimal SueldoOrdinario
		{
			get
			{
				return this._SueldoOrdinario;
			}
			set
			{
				if ((this._SueldoOrdinario != value))
				{
					this.OnSueldoOrdinarioChanging(value);
					this.SendPropertyChanging();
					this._SueldoOrdinario = value;
					this.SendPropertyChanged("SueldoOrdinario");
					this.OnSueldoOrdinarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NivelAcademico", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string NivelAcademico
		{
			get
			{
				return this._NivelAcademico;
			}
			set
			{
				if ((this._NivelAcademico != value))
				{
					this.OnNivelAcademicoChanging(value);
					this.SendPropertyChanging();
					this._NivelAcademico = value;
					this.SendPropertyChanged("NivelAcademico");
					this.OnNivelAcademicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Bit")]
		public System.Nullable<bool> Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleado_HoraExtra", Storage="_HoraExtra", ThisKey="Identidad", OtherKey="IdentidadEmpleado")]
		public EntitySet<HoraExtra> HoraExtra
		{
			get
			{
				return this._HoraExtra;
			}
			set
			{
				this._HoraExtra.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleado_HoraFaltada", Storage="_HoraFaltada", ThisKey="Identidad", OtherKey="IdentidadEmpleado")]
		public EntitySet<HoraFaltada> HoraFaltada
		{
			get
			{
				return this._HoraFaltada;
			}
			set
			{
				this._HoraFaltada.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleado_PlanillaFinal", Storage="_PlanillaFinal", ThisKey="Identidad", OtherKey="IdentidadEmpleado")]
		public EntitySet<PlanillaFinal> PlanillaFinal
		{
			get
			{
				return this._PlanillaFinal;
			}
			set
			{
				this._PlanillaFinal.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleado_PrestacionLaboral", Storage="_PrestacionLaboral", ThisKey="Identidad", OtherKey="IdentidadEmpleado")]
		public EntitySet<PrestacionLaboral> PrestacionLaboral
		{
			get
			{
				return this._PrestacionLaboral;
			}
			set
			{
				this._PrestacionLaboral.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleado_TelefonoEmpleado", Storage="_TelefonoEmpleado", ThisKey="Identidad", OtherKey="IdentidadEmpleado")]
		public EntitySet<TelefonoEmpleado> TelefonoEmpleado
		{
			get
			{
				return this._TelefonoEmpleado;
			}
			set
			{
				this._TelefonoEmpleado.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleado_Usuario", Storage="_Usuario", ThisKey="Identidad", OtherKey="IdentidadEmpleado")]
		public EntitySet<Usuario> Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				this._Usuario.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cargo_Empleado", Storage="_Cargo", ThisKey="CodigoCargo", OtherKey="Codigo", IsForeignKey=true)]
		public Cargo Cargo
		{
			get
			{
				return this._Cargo.Entity;
			}
			set
			{
				Cargo previousValue = this._Cargo.Entity;
				if (((previousValue != value) 
							|| (this._Cargo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cargo.Entity = null;
						previousValue.Empleado.Remove(this);
					}
					this._Cargo.Entity = value;
					if ((value != null))
					{
						value.Empleado.Add(this);
						this._CodigoCargo = value.Codigo;
					}
					else
					{
						this._CodigoCargo = default(string);
					}
					this.SendPropertyChanged("Cargo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoraExtra(HoraExtra entity)
		{
			this.SendPropertyChanging();
			entity.Empleado = this;
		}
		
		private void detach_HoraExtra(HoraExtra entity)
		{
			this.SendPropertyChanging();
			entity.Empleado = null;
		}
		
		private void attach_HoraFaltada(HoraFaltada entity)
		{
			this.SendPropertyChanging();
			entity.Empleado = this;
		}
		
		private void detach_HoraFaltada(HoraFaltada entity)
		{
			this.SendPropertyChanging();
			entity.Empleado = null;
		}
		
		private void attach_PlanillaFinal(PlanillaFinal entity)
		{
			this.SendPropertyChanging();
			entity.Empleado = this;
		}
		
		private void detach_PlanillaFinal(PlanillaFinal entity)
		{
			this.SendPropertyChanging();
			entity.Empleado = null;
		}
		
		private void attach_PrestacionLaboral(PrestacionLaboral entity)
		{
			this.SendPropertyChanging();
			entity.Empleado = this;
		}
		
		private void detach_PrestacionLaboral(PrestacionLaboral entity)
		{
			this.SendPropertyChanging();
			entity.Empleado = null;
		}
		
		private void attach_TelefonoEmpleado(TelefonoEmpleado entity)
		{
			this.SendPropertyChanging();
			entity.Empleado = this;
		}
		
		private void detach_TelefonoEmpleado(TelefonoEmpleado entity)
		{
			this.SendPropertyChanging();
			entity.Empleado = null;
		}
		
		private void attach_Usuario(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Empleado = this;
		}
		
		private void detach_Usuario(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Empleado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Planilla.HoraExtra")]
	public partial class HoraExtra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Codigo;
		
		private string _IdentidadEmpleado;
		
		private int _TotalHora;
		
		private string _CodigoPorcentajeHoraExtra;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private EntityRef<Empleado> _Empleado;
		
		private EntityRef<PorcentajeHoraExtra> _PorcentajeHoraExtra;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    partial void OnIdentidadEmpleadoChanging(string value);
    partial void OnIdentidadEmpleadoChanged();
    partial void OnTotalHoraChanging(int value);
    partial void OnTotalHoraChanged();
    partial void OnCodigoPorcentajeHoraExtraChanging(string value);
    partial void OnCodigoPorcentajeHoraExtraChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    #endregion
		
		public HoraExtra()
		{
			this._Empleado = default(EntityRef<Empleado>);
			this._PorcentajeHoraExtra = default(EntityRef<PorcentajeHoraExtra>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdentidadEmpleado", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string IdentidadEmpleado
		{
			get
			{
				return this._IdentidadEmpleado;
			}
			set
			{
				if ((this._IdentidadEmpleado != value))
				{
					if (this._Empleado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdentidadEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._IdentidadEmpleado = value;
					this.SendPropertyChanged("IdentidadEmpleado");
					this.OnIdentidadEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalHora", DbType="Int NOT NULL")]
		public int TotalHora
		{
			get
			{
				return this._TotalHora;
			}
			set
			{
				if ((this._TotalHora != value))
				{
					this.OnTotalHoraChanging(value);
					this.SendPropertyChanging();
					this._TotalHora = value;
					this.SendPropertyChanged("TotalHora");
					this.OnTotalHoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoPorcentajeHoraExtra", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string CodigoPorcentajeHoraExtra
		{
			get
			{
				return this._CodigoPorcentajeHoraExtra;
			}
			set
			{
				if ((this._CodigoPorcentajeHoraExtra != value))
				{
					if (this._PorcentajeHoraExtra.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodigoPorcentajeHoraExtraChanging(value);
					this.SendPropertyChanging();
					this._CodigoPorcentajeHoraExtra = value;
					this.SendPropertyChanged("CodigoPorcentajeHoraExtra");
					this.OnCodigoPorcentajeHoraExtraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleado_HoraExtra", Storage="_Empleado", ThisKey="IdentidadEmpleado", OtherKey="Identidad", IsForeignKey=true)]
		public Empleado Empleado
		{
			get
			{
				return this._Empleado.Entity;
			}
			set
			{
				Empleado previousValue = this._Empleado.Entity;
				if (((previousValue != value) 
							|| (this._Empleado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Empleado.Entity = null;
						previousValue.HoraExtra.Remove(this);
					}
					this._Empleado.Entity = value;
					if ((value != null))
					{
						value.HoraExtra.Add(this);
						this._IdentidadEmpleado = value.Identidad;
					}
					else
					{
						this._IdentidadEmpleado = default(string);
					}
					this.SendPropertyChanged("Empleado");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PorcentajeHoraExtra_HoraExtra", Storage="_PorcentajeHoraExtra", ThisKey="CodigoPorcentajeHoraExtra", OtherKey="Codigo", IsForeignKey=true)]
		public PorcentajeHoraExtra PorcentajeHoraExtra
		{
			get
			{
				return this._PorcentajeHoraExtra.Entity;
			}
			set
			{
				PorcentajeHoraExtra previousValue = this._PorcentajeHoraExtra.Entity;
				if (((previousValue != value) 
							|| (this._PorcentajeHoraExtra.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PorcentajeHoraExtra.Entity = null;
						previousValue.HoraExtra.Remove(this);
					}
					this._PorcentajeHoraExtra.Entity = value;
					if ((value != null))
					{
						value.HoraExtra.Add(this);
						this._CodigoPorcentajeHoraExtra = value.Codigo;
					}
					else
					{
						this._CodigoPorcentajeHoraExtra = default(string);
					}
					this.SendPropertyChanged("PorcentajeHoraExtra");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Planilla.HoraFaltada")]
	public partial class HoraFaltada : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Codigo;
		
		private string _IdentidadEmpleado;
		
		private int _TotalHora;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private string _Motivo;
		
		private EntityRef<Empleado> _Empleado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    partial void OnIdentidadEmpleadoChanging(string value);
    partial void OnIdentidadEmpleadoChanged();
    partial void OnTotalHoraChanging(int value);
    partial void OnTotalHoraChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    partial void OnMotivoChanging(string value);
    partial void OnMotivoChanged();
    #endregion
		
		public HoraFaltada()
		{
			this._Empleado = default(EntityRef<Empleado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdentidadEmpleado", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string IdentidadEmpleado
		{
			get
			{
				return this._IdentidadEmpleado;
			}
			set
			{
				if ((this._IdentidadEmpleado != value))
				{
					if (this._Empleado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdentidadEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._IdentidadEmpleado = value;
					this.SendPropertyChanged("IdentidadEmpleado");
					this.OnIdentidadEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalHora", DbType="Int NOT NULL")]
		public int TotalHora
		{
			get
			{
				return this._TotalHora;
			}
			set
			{
				if ((this._TotalHora != value))
				{
					this.OnTotalHoraChanging(value);
					this.SendPropertyChanging();
					this._TotalHora = value;
					this.SendPropertyChanged("TotalHora");
					this.OnTotalHoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Motivo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Motivo
		{
			get
			{
				return this._Motivo;
			}
			set
			{
				if ((this._Motivo != value))
				{
					this.OnMotivoChanging(value);
					this.SendPropertyChanging();
					this._Motivo = value;
					this.SendPropertyChanged("Motivo");
					this.OnMotivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleado_HoraFaltada", Storage="_Empleado", ThisKey="IdentidadEmpleado", OtherKey="Identidad", IsForeignKey=true)]
		public Empleado Empleado
		{
			get
			{
				return this._Empleado.Entity;
			}
			set
			{
				Empleado previousValue = this._Empleado.Entity;
				if (((previousValue != value) 
							|| (this._Empleado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Empleado.Entity = null;
						previousValue.HoraFaltada.Remove(this);
					}
					this._Empleado.Entity = value;
					if ((value != null))
					{
						value.HoraFaltada.Add(this);
						this._IdentidadEmpleado = value.Identidad;
					}
					else
					{
						this._IdentidadEmpleado = default(string);
					}
					this.SendPropertyChanged("Empleado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Planilla.IHSS")]
	public partial class IHSS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Codigo;
		
		private decimal _GastosMedicos;
		
		private decimal _SalarioTecho;
		
		private System.Nullable<System.DateTime> _Fecha;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    partial void OnGastosMedicosChanging(decimal value);
    partial void OnGastosMedicosChanged();
    partial void OnSalarioTechoChanging(decimal value);
    partial void OnSalarioTechoChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    #endregion
		
		public IHSS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GastosMedicos", DbType="Decimal(10,2) NOT NULL")]
		public decimal GastosMedicos
		{
			get
			{
				return this._GastosMedicos;
			}
			set
			{
				if ((this._GastosMedicos != value))
				{
					this.OnGastosMedicosChanging(value);
					this.SendPropertyChanging();
					this._GastosMedicos = value;
					this.SendPropertyChanged("GastosMedicos");
					this.OnGastosMedicosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalarioTecho", DbType="Decimal(10,2) NOT NULL")]
		public decimal SalarioTecho
		{
			get
			{
				return this._SalarioTecho;
			}
			set
			{
				if ((this._SalarioTecho != value))
				{
					this.OnSalarioTechoChanging(value);
					this.SendPropertyChanging();
					this._SalarioTecho = value;
					this.SendPropertyChanged("SalarioTecho");
					this.OnSalarioTechoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Planilla.PlanillaFinal")]
	public partial class PlanillaFinal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Codigo;
		
		private System.Nullable<System.DateTime> _CodigoPlanillaFinal;
		
		private string _IdentidadEmpleado;
		
		private System.Nullable<decimal> _SueldoOrdinario;
		
		private System.Nullable<decimal> _IHSS;
		
		private System.Nullable<decimal> _RAP;
		
		private System.Nullable<decimal> _HorasFaltadas;
		
		private System.Nullable<decimal> _HorasExtras;
		
		private System.Nullable<decimal> _SueldoNeto;
		
		private EntityRef<Empleado> _Empleado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    partial void OnCodigoPlanillaFinalChanging(System.Nullable<System.DateTime> value);
    partial void OnCodigoPlanillaFinalChanged();
    partial void OnIdentidadEmpleadoChanging(string value);
    partial void OnIdentidadEmpleadoChanged();
    partial void OnSueldoOrdinarioChanging(System.Nullable<decimal> value);
    partial void OnSueldoOrdinarioChanged();
    partial void OnIHSSChanging(System.Nullable<decimal> value);
    partial void OnIHSSChanged();
    partial void OnRAPChanging(System.Nullable<decimal> value);
    partial void OnRAPChanged();
    partial void OnHorasFaltadasChanging(System.Nullable<decimal> value);
    partial void OnHorasFaltadasChanged();
    partial void OnHorasExtrasChanging(System.Nullable<decimal> value);
    partial void OnHorasExtrasChanged();
    partial void OnSueldoNetoChanging(System.Nullable<decimal> value);
    partial void OnSueldoNetoChanged();
    #endregion
		
		public PlanillaFinal()
		{
			this._Empleado = default(EntityRef<Empleado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoPlanillaFinal", DbType="Date")]
		public System.Nullable<System.DateTime> CodigoPlanillaFinal
		{
			get
			{
				return this._CodigoPlanillaFinal;
			}
			set
			{
				if ((this._CodigoPlanillaFinal != value))
				{
					this.OnCodigoPlanillaFinalChanging(value);
					this.SendPropertyChanging();
					this._CodigoPlanillaFinal = value;
					this.SendPropertyChanged("CodigoPlanillaFinal");
					this.OnCodigoPlanillaFinalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdentidadEmpleado", DbType="Char(15)")]
		public string IdentidadEmpleado
		{
			get
			{
				return this._IdentidadEmpleado;
			}
			set
			{
				if ((this._IdentidadEmpleado != value))
				{
					if (this._Empleado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdentidadEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._IdentidadEmpleado = value;
					this.SendPropertyChanged("IdentidadEmpleado");
					this.OnIdentidadEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SueldoOrdinario", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> SueldoOrdinario
		{
			get
			{
				return this._SueldoOrdinario;
			}
			set
			{
				if ((this._SueldoOrdinario != value))
				{
					this.OnSueldoOrdinarioChanging(value);
					this.SendPropertyChanging();
					this._SueldoOrdinario = value;
					this.SendPropertyChanged("SueldoOrdinario");
					this.OnSueldoOrdinarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IHSS", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> IHSS
		{
			get
			{
				return this._IHSS;
			}
			set
			{
				if ((this._IHSS != value))
				{
					this.OnIHSSChanging(value);
					this.SendPropertyChanging();
					this._IHSS = value;
					this.SendPropertyChanged("IHSS");
					this.OnIHSSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RAP", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> RAP
		{
			get
			{
				return this._RAP;
			}
			set
			{
				if ((this._RAP != value))
				{
					this.OnRAPChanging(value);
					this.SendPropertyChanging();
					this._RAP = value;
					this.SendPropertyChanged("RAP");
					this.OnRAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HorasFaltadas", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> HorasFaltadas
		{
			get
			{
				return this._HorasFaltadas;
			}
			set
			{
				if ((this._HorasFaltadas != value))
				{
					this.OnHorasFaltadasChanging(value);
					this.SendPropertyChanging();
					this._HorasFaltadas = value;
					this.SendPropertyChanged("HorasFaltadas");
					this.OnHorasFaltadasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HorasExtras", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> HorasExtras
		{
			get
			{
				return this._HorasExtras;
			}
			set
			{
				if ((this._HorasExtras != value))
				{
					this.OnHorasExtrasChanging(value);
					this.SendPropertyChanging();
					this._HorasExtras = value;
					this.SendPropertyChanged("HorasExtras");
					this.OnHorasExtrasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SueldoNeto", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> SueldoNeto
		{
			get
			{
				return this._SueldoNeto;
			}
			set
			{
				if ((this._SueldoNeto != value))
				{
					this.OnSueldoNetoChanging(value);
					this.SendPropertyChanging();
					this._SueldoNeto = value;
					this.SendPropertyChanged("SueldoNeto");
					this.OnSueldoNetoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleado_PlanillaFinal", Storage="_Empleado", ThisKey="IdentidadEmpleado", OtherKey="Identidad", IsForeignKey=true)]
		public Empleado Empleado
		{
			get
			{
				return this._Empleado.Entity;
			}
			set
			{
				Empleado previousValue = this._Empleado.Entity;
				if (((previousValue != value) 
							|| (this._Empleado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Empleado.Entity = null;
						previousValue.PlanillaFinal.Remove(this);
					}
					this._Empleado.Entity = value;
					if ((value != null))
					{
						value.PlanillaFinal.Add(this);
						this._IdentidadEmpleado = value.Identidad;
					}
					else
					{
						this._IdentidadEmpleado = default(string);
					}
					this.SendPropertyChanged("Empleado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Planilla.PorcentajeHoraExtra")]
	public partial class PorcentajeHoraExtra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Codigo;
		
		private string _TipoHora;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private EntitySet<HoraExtra> _HoraExtra;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(string value);
    partial void OnCodigoChanged();
    partial void OnTipoHoraChanging(string value);
    partial void OnTipoHoraChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    #endregion
		
		public PorcentajeHoraExtra()
		{
			this._HoraExtra = new EntitySet<HoraExtra>(new Action<HoraExtra>(this.attach_HoraExtra), new Action<HoraExtra>(this.detach_HoraExtra));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="Char(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoHora", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string TipoHora
		{
			get
			{
				return this._TipoHora;
			}
			set
			{
				if ((this._TipoHora != value))
				{
					this.OnTipoHoraChanging(value);
					this.SendPropertyChanging();
					this._TipoHora = value;
					this.SendPropertyChanged("TipoHora");
					this.OnTipoHoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PorcentajeHoraExtra_HoraExtra", Storage="_HoraExtra", ThisKey="Codigo", OtherKey="CodigoPorcentajeHoraExtra")]
		public EntitySet<HoraExtra> HoraExtra
		{
			get
			{
				return this._HoraExtra;
			}
			set
			{
				this._HoraExtra.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoraExtra(HoraExtra entity)
		{
			this.SendPropertyChanging();
			entity.PorcentajeHoraExtra = this;
		}
		
		private void detach_HoraExtra(HoraExtra entity)
		{
			this.SendPropertyChanging();
			entity.PorcentajeHoraExtra = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Planilla.PrestacionLaboral")]
	public partial class PrestacionLaboral : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Codigo;
		
		private string _IdentidadEmpleado;
		
		private decimal _Cesantia;
		
		private decimal _Vacaciones;
		
		private decimal _DecimoTercero;
		
		private decimal _DecimoCuarto;
		
		private string _Motivo;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private EntityRef<PrestacionLaboralEmbarazo> _PrestacionLaboralEmbarazo;
		
		private EntityRef<Empleado> _Empleado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    partial void OnIdentidadEmpleadoChanging(string value);
    partial void OnIdentidadEmpleadoChanged();
    partial void OnCesantiaChanging(decimal value);
    partial void OnCesantiaChanged();
    partial void OnVacacionesChanging(decimal value);
    partial void OnVacacionesChanged();
    partial void OnDecimoTerceroChanging(decimal value);
    partial void OnDecimoTerceroChanged();
    partial void OnDecimoCuartoChanging(decimal value);
    partial void OnDecimoCuartoChanged();
    partial void OnMotivoChanging(string value);
    partial void OnMotivoChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    #endregion
		
		public PrestacionLaboral()
		{
			this._PrestacionLaboralEmbarazo = default(EntityRef<PrestacionLaboralEmbarazo>);
			this._Empleado = default(EntityRef<Empleado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdentidadEmpleado", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string IdentidadEmpleado
		{
			get
			{
				return this._IdentidadEmpleado;
			}
			set
			{
				if ((this._IdentidadEmpleado != value))
				{
					if (this._Empleado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdentidadEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._IdentidadEmpleado = value;
					this.SendPropertyChanged("IdentidadEmpleado");
					this.OnIdentidadEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cesantia", DbType="Decimal(10,2) NOT NULL")]
		public decimal Cesantia
		{
			get
			{
				return this._Cesantia;
			}
			set
			{
				if ((this._Cesantia != value))
				{
					this.OnCesantiaChanging(value);
					this.SendPropertyChanging();
					this._Cesantia = value;
					this.SendPropertyChanged("Cesantia");
					this.OnCesantiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vacaciones", DbType="Decimal(10,2) NOT NULL")]
		public decimal Vacaciones
		{
			get
			{
				return this._Vacaciones;
			}
			set
			{
				if ((this._Vacaciones != value))
				{
					this.OnVacacionesChanging(value);
					this.SendPropertyChanging();
					this._Vacaciones = value;
					this.SendPropertyChanged("Vacaciones");
					this.OnVacacionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DecimoTercero", DbType="Decimal(10,2) NOT NULL")]
		public decimal DecimoTercero
		{
			get
			{
				return this._DecimoTercero;
			}
			set
			{
				if ((this._DecimoTercero != value))
				{
					this.OnDecimoTerceroChanging(value);
					this.SendPropertyChanging();
					this._DecimoTercero = value;
					this.SendPropertyChanged("DecimoTercero");
					this.OnDecimoTerceroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DecimoCuarto", DbType="Decimal(10,2) NOT NULL")]
		public decimal DecimoCuarto
		{
			get
			{
				return this._DecimoCuarto;
			}
			set
			{
				if ((this._DecimoCuarto != value))
				{
					this.OnDecimoCuartoChanging(value);
					this.SendPropertyChanging();
					this._DecimoCuarto = value;
					this.SendPropertyChanged("DecimoCuarto");
					this.OnDecimoCuartoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Motivo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Motivo
		{
			get
			{
				return this._Motivo;
			}
			set
			{
				if ((this._Motivo != value))
				{
					this.OnMotivoChanging(value);
					this.SendPropertyChanging();
					this._Motivo = value;
					this.SendPropertyChanged("Motivo");
					this.OnMotivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PrestacionLaboral_PrestacionLaboralEmbarazo", Storage="_PrestacionLaboralEmbarazo", ThisKey="Codigo", OtherKey="Codigo", IsUnique=true, IsForeignKey=false)]
		public PrestacionLaboralEmbarazo PrestacionLaboralEmbarazo
		{
			get
			{
				return this._PrestacionLaboralEmbarazo.Entity;
			}
			set
			{
				PrestacionLaboralEmbarazo previousValue = this._PrestacionLaboralEmbarazo.Entity;
				if (((previousValue != value) 
							|| (this._PrestacionLaboralEmbarazo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PrestacionLaboralEmbarazo.Entity = null;
						previousValue.PrestacionLaboral = null;
					}
					this._PrestacionLaboralEmbarazo.Entity = value;
					if ((value != null))
					{
						value.PrestacionLaboral = this;
					}
					this.SendPropertyChanged("PrestacionLaboralEmbarazo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleado_PrestacionLaboral", Storage="_Empleado", ThisKey="IdentidadEmpleado", OtherKey="Identidad", IsForeignKey=true)]
		public Empleado Empleado
		{
			get
			{
				return this._Empleado.Entity;
			}
			set
			{
				Empleado previousValue = this._Empleado.Entity;
				if (((previousValue != value) 
							|| (this._Empleado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Empleado.Entity = null;
						previousValue.PrestacionLaboral.Remove(this);
					}
					this._Empleado.Entity = value;
					if ((value != null))
					{
						value.PrestacionLaboral.Add(this);
						this._IdentidadEmpleado = value.Identidad;
					}
					else
					{
						this._IdentidadEmpleado = default(string);
					}
					this.SendPropertyChanged("Empleado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Planilla.PrestacionLaboralEmbarazo")]
	public partial class PrestacionLaboralEmbarazo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Codigo;
		
		private string _IdentidadEmpleado;
		
		private decimal _Prenatal;
		
		private decimal _Lactancia;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private EntityRef<PrestacionLaboral> _PrestacionLaboral;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    partial void OnIdentidadEmpleadoChanging(string value);
    partial void OnIdentidadEmpleadoChanged();
    partial void OnPrenatalChanging(decimal value);
    partial void OnPrenatalChanged();
    partial void OnLactanciaChanging(decimal value);
    partial void OnLactanciaChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    #endregion
		
		public PrestacionLaboralEmbarazo()
		{
			this._PrestacionLaboral = default(EntityRef<PrestacionLaboral>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					if (this._PrestacionLaboral.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdentidadEmpleado", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string IdentidadEmpleado
		{
			get
			{
				return this._IdentidadEmpleado;
			}
			set
			{
				if ((this._IdentidadEmpleado != value))
				{
					this.OnIdentidadEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._IdentidadEmpleado = value;
					this.SendPropertyChanged("IdentidadEmpleado");
					this.OnIdentidadEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenatal", DbType="Decimal(10,2) NOT NULL")]
		public decimal Prenatal
		{
			get
			{
				return this._Prenatal;
			}
			set
			{
				if ((this._Prenatal != value))
				{
					this.OnPrenatalChanging(value);
					this.SendPropertyChanging();
					this._Prenatal = value;
					this.SendPropertyChanged("Prenatal");
					this.OnPrenatalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lactancia", DbType="Decimal(10,2) NOT NULL")]
		public decimal Lactancia
		{
			get
			{
				return this._Lactancia;
			}
			set
			{
				if ((this._Lactancia != value))
				{
					this.OnLactanciaChanging(value);
					this.SendPropertyChanging();
					this._Lactancia = value;
					this.SendPropertyChanged("Lactancia");
					this.OnLactanciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PrestacionLaboral_PrestacionLaboralEmbarazo", Storage="_PrestacionLaboral", ThisKey="Codigo", OtherKey="Codigo", IsForeignKey=true)]
		public PrestacionLaboral PrestacionLaboral
		{
			get
			{
				return this._PrestacionLaboral.Entity;
			}
			set
			{
				PrestacionLaboral previousValue = this._PrestacionLaboral.Entity;
				if (((previousValue != value) 
							|| (this._PrestacionLaboral.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PrestacionLaboral.Entity = null;
						previousValue.PrestacionLaboralEmbarazo = null;
					}
					this._PrestacionLaboral.Entity = value;
					if ((value != null))
					{
						value.PrestacionLaboralEmbarazo = this;
						this._Codigo = value.Codigo;
					}
					else
					{
						this._Codigo = default(int);
					}
					this.SendPropertyChanged("PrestacionLaboral");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Planilla.RAP")]
	public partial class RAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Codigo;
		
		private decimal _Techo;
		
		private System.Nullable<System.DateTime> _Fecha;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    partial void OnTechoChanging(decimal value);
    partial void OnTechoChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    #endregion
		
		public RAP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Techo", DbType="Decimal(10,2) NOT NULL")]
		public decimal Techo
		{
			get
			{
				return this._Techo;
			}
			set
			{
				if ((this._Techo != value))
				{
					this.OnTechoChanging(value);
					this.SendPropertyChanging();
					this._Techo = value;
					this.SendPropertyChanged("Techo");
					this.OnTechoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Planilla.TelefonoEmpleado")]
	public partial class TelefonoEmpleado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Codigo;
		
		private string _IdentidadEmpleado;
		
		private string _Telefono;
		
		private System.DateTime _Fecha;
		
		private EntityRef<Empleado> _Empleado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    partial void OnIdentidadEmpleadoChanging(string value);
    partial void OnIdentidadEmpleadoChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    #endregion
		
		public TelefonoEmpleado()
		{
			this._Empleado = default(EntityRef<Empleado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdentidadEmpleado", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string IdentidadEmpleado
		{
			get
			{
				return this._IdentidadEmpleado;
			}
			set
			{
				if ((this._IdentidadEmpleado != value))
				{
					if (this._Empleado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdentidadEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._IdentidadEmpleado = value;
					this.SendPropertyChanged("IdentidadEmpleado");
					this.OnIdentidadEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="Char(9) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleado_TelefonoEmpleado", Storage="_Empleado", ThisKey="IdentidadEmpleado", OtherKey="Identidad", IsForeignKey=true)]
		public Empleado Empleado
		{
			get
			{
				return this._Empleado.Entity;
			}
			set
			{
				Empleado previousValue = this._Empleado.Entity;
				if (((previousValue != value) 
							|| (this._Empleado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Empleado.Entity = null;
						previousValue.TelefonoEmpleado.Remove(this);
					}
					this._Empleado.Entity = value;
					if ((value != null))
					{
						value.TelefonoEmpleado.Add(this);
						this._IdentidadEmpleado = value.Identidad;
					}
					else
					{
						this._IdentidadEmpleado = default(string);
					}
					this.SendPropertyChanged("Empleado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Planilla.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Codigo;
		
		private string _Usuario1;
		
		private string _Contraseña;
		
		private string _IdentidadEmpleado;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private System.Nullable<bool> _Estado;
		
		private EntityRef<Empleado> _Empleado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    partial void OnUsuario1Changing(string value);
    partial void OnUsuario1Changed();
    partial void OnContraseñaChanging(string value);
    partial void OnContraseñaChanged();
    partial void OnIdentidadEmpleadoChanging(string value);
    partial void OnIdentidadEmpleadoChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    partial void OnEstadoChanging(System.Nullable<bool> value);
    partial void OnEstadoChanged();
    #endregion
		
		public Usuario()
		{
			this._Empleado = default(EntityRef<Empleado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Usuario", Storage="_Usuario1", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Usuario1
		{
			get
			{
				return this._Usuario1;
			}
			set
			{
				if ((this._Usuario1 != value))
				{
					this.OnUsuario1Changing(value);
					this.SendPropertyChanging();
					this._Usuario1 = value;
					this.SendPropertyChanged("Usuario1");
					this.OnUsuario1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this.OnContraseñaChanging(value);
					this.SendPropertyChanging();
					this._Contraseña = value;
					this.SendPropertyChanged("Contraseña");
					this.OnContraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdentidadEmpleado", DbType="Char(15)")]
		public string IdentidadEmpleado
		{
			get
			{
				return this._IdentidadEmpleado;
			}
			set
			{
				if ((this._IdentidadEmpleado != value))
				{
					if (this._Empleado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdentidadEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._IdentidadEmpleado = value;
					this.SendPropertyChanged("IdentidadEmpleado");
					this.OnIdentidadEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Bit")]
		public System.Nullable<bool> Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleado_Usuario", Storage="_Empleado", ThisKey="IdentidadEmpleado", OtherKey="Identidad", IsForeignKey=true)]
		public Empleado Empleado
		{
			get
			{
				return this._Empleado.Entity;
			}
			set
			{
				Empleado previousValue = this._Empleado.Entity;
				if (((previousValue != value) 
							|| (this._Empleado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Empleado.Entity = null;
						previousValue.Usuario.Remove(this);
					}
					this._Empleado.Entity = value;
					if ((value != null))
					{
						value.Usuario.Add(this);
						this._IdentidadEmpleado = value.Identidad;
					}
					else
					{
						this._IdentidadEmpleado = default(string);
					}
					this.SendPropertyChanged("Empleado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
